// ───────────────────────────────────────────────────────────────────────────
// supabase-sync — bridges Zustand store actions with Supabase persistence
// ───────────────────────────────────────────────────────────────────────────
//
// This module mirrors the legacy `firestoreSync` API but routes every write
// to the appropriate Supabase service. It is imported by `@/lib/store` so
// every store action persists to Supabase in the background.
//
// CRITICAL: Every write method now SURFACES errors to the user via toast.
// Previously, `safeQuery` swallowed errors silently — data appeared in the UI
// (via the optimistic Zustand update) but never landed in the database. Now
// the service `create` methods throw on error, and these methods catch the
// error, log it, AND toast the user so they know the save failed.
//
// Realtime subscriptions in `SupabaseSyncProvider` will catch up the local
// state once a successful write lands in the database.
// ───────────────────────────────────────────────────────────────────────────

import {
  patientService,
  vitalService,
  medicationService,
  screeningService,
  nutritionService,
  complaintService,
  socialService,
  acpService,
  chatService,
  caregiverService,
  familyMeetingService,
  familyCoordinationNoteService,
  emergencyContactService,
  financialSupportService,
  transportRecordService,
  familySupportMaterialService,
  referralLetterService,
  palliativeResumeService,
  supabase,
  isValidUuid,
  validUuidOrUndefined,
} from '@/services/supabase';
import { toast } from '@/hooks/use-toast';

/** Show a destructive toast for a save failure. */
function toastSaveError(label: string, err: unknown) {
  const msg = err instanceof Error ? err.message : String(err);
  console.error(`[SupabaseSync] ${label} FAILED:`, msg);
  toast({
    title: 'Gagal menyimpan ke database',
    description: `${label}: ${msg}`,
    variant: 'destructive',
  });
}

/** Normalize a clinical-alert severity to the DB-allowed enum. */
function normalizeSeverity(raw: unknown): 'hijau' | 'kuning' | 'merah' {
  if (typeof raw !== 'string') return 'kuning';
  const s = raw.toLowerCase();
  if (s === 'hijau' || s === 'green' || s === 'info' || s === 'low') return 'hijau';
  if (s === 'merah' || s === 'red' || s === 'high' || s === 'critical') return 'merah';
  return 'kuning';
}

export const supabaseSync = {
  // ── Patients ───────────────────────────────────────────────────────────
  /**
   * Create a patient in Supabase. Returns the created patient (with the real
   * UUID generated by Supabase), or null on failure.
   *
   * IMPORTANT: The caller (store.ts → addPalliativePatient) MUST use the
   * returned object's `id` to update the local Zustand state so that all
   * subsequent sub-record inserts (vitals, screenings, etc.) use the real
   * UUID as `patient_id` — never a custom string like "pp-...".
   */
  async addPatient(data: Record<string, unknown>): Promise<{ id: string; [k: string]: unknown } | null> {
    try {
      const created = await patientService.create(data as any);
      if (created) {
        console.log('[supabaseSync.addPatient] created patient with real UUID:', created.id);
        return created as any;
      }
      return null;
    } catch (err) {
      toastSaveError('Tambah Pasien', err);
      return null;
    }
  },

  async updatePatient(id: string, data: Record<string, unknown>): Promise<void> {
    try {
      await patientService.update(id, data as any);
    } catch (err) {
      toastSaveError('Update Pasien', err);
    }
  },

  async deletePatient(id: string): Promise<void> {
    try {
      await patientService.remove(id);
    } catch (err) {
      toastSaveError('Hapus Pasien', err);
    }
  },

  // ── Vital signs (TTV) ──────────────────────────────────────────────────
  async addTTV(patientId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await vitalService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan TTV', err);
    }
  },

  // ── Medications (Obat) ─────────────────────────────────────────────────
  async addObat(patientId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await medicationService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Obat', err);
    }
  },

  async updateObat(patientId: string, medId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await medicationService.update(medId, data as any);
    } catch (err) {
      toastSaveError('Update Obat', err);
    }
  },

  // ── Advance Care Planning (ACP) ────────────────────────────────────────
  async addACP(patientId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await acpService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan ACP', err);
    }
  },

  async updateACP(patientId: string, planId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await acpService.update(planId, data as any);
    } catch (err) {
      toastSaveError('Update ACP', err);
    }
  },

  // ── Screenings (Skrining) ──────────────────────────────────────────────
  async addSkrining(patientId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await screeningService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Skrining', err);
    }
  },

  // ── Nutrition (Nutrisi) ────────────────────────────────────────────────
  async addNutrisi(patientId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await nutritionService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Nutrisi', err);
    }
  },

  // ── Chat messages ──────────────────────────────────────────────────────
  /**
   * Resolve a real chat-room UUID for the (patientId, doctorId) pair, then
   * send the message. The frontend uses a composite `roomId` string like
   * `${patientId}_${doctorId}` for local filtering — that's NOT a UUID and
   * cannot be used as the `room_id` FK. We call `getOrCreateRoom` to get the
   * real UUID from the `chat_rooms` table.
   */
  async addChatMessage(patientId: string, data: Record<string, unknown>): Promise<void> {
    try {
      if (!isValidUuid(patientId)) {
        console.error('[supabaseSync.addChatMessage] ABORTED — patientId is not a valid UUID:', patientId);
        return;
      }
      const localRoomId = data.roomId as string | undefined;
      const senderRole = data.senderRole as string | undefined;
      const senderId = data.senderId as string | undefined;
      // If the doctor is the sender, use their id for the room lookup.
      const doctorId = senderRole === 'doctor' ? senderId : undefined;
      const validDoctorId = validUuidOrUndefined(doctorId);

      // Resolve a real UUID room_id. If localRoomId is already a UUID, use it
      // directly; otherwise get-or-create one.
      let realRoomId: string | null = null;
      if (localRoomId && isValidUuid(localRoomId)) {
        realRoomId = localRoomId;
      } else {
        realRoomId = await chatService.getOrCreateRoom(patientId, validDoctorId ?? '');
      }
      if (!realRoomId) {
        throw new Error('Could not resolve or create a chat room');
      }

      // Inject patient_id and doctor_id (as UUIDs) into the payload so the
      // messages table records who the conversation is between. chatService
      // .sendMessage will pick these up via messageToDb and validate them.
      const enrichedData = {
        ...(data as any),
        palliativePatientId: patientId, // → patient_id column (uuid)
        doctorId: validDoctorId,        // → doctor_id column (nullable uuid)
      };
      await chatService.sendMessage(realRoomId, enrichedData as any);
    } catch (err) {
      toastSaveError('Kirim Pesan Chat', err);
    }
  },

  async updateChatMessage(patientId: string, msgId: string, data: Record<string, unknown>): Promise<void> {
    try {
      if ('status' in data && data.status === 'read') {
        await chatService.markRead(msgId);
      }
      // Persist form status changes (e.g. sent → submitted once the patient
      // fills a Form TTV / Form Keluhan) — without this the badge only
      // updates in the local session and reverts on refresh.
      if ('formData' in data && data.formData) {
        await chatService.updateFormData(msgId, data.formData as any);
      }
    } catch (err) {
      console.error('[SupabaseSync] updateChatMessage:', err);
    }
  },

  // ── Clinical alerts ────────────────────────────────────────────────────
  async addClinicalAlert(patientId: string, data: Record<string, unknown>): Promise<void> {
    try {
      if (!isValidUuid(patientId)) {
        console.error('[supabaseSync.addClinicalAlert] ABORTED — patientId is not a valid UUID:', patientId);
        return;
      }
      // Build the values JSONB payload with rich EWS fields.
      const valuesPayload: Record<string, any> = {};
      if (data.severityLevel) valuesPayload.severityLevel = data.severityLevel;
      if (data.status) valuesPayload.status = data.status;
      if (data.sourceModule) valuesPayload.sourceModule = data.sourceModule;
      if (data.sourceRecordId) valuesPayload.sourceRecordId = data.sourceRecordId;
      if (data.kategori) valuesPayload.kategori = data.kategori;
      if (data.recommendation) valuesPayload.recommendation = data.recommendation;
      if (data.doctorId) valuesPayload.doctorId = data.doctorId;
      if (data.notes) valuesPayload.notes = data.notes;

      const { error } = await supabase.from('clinical_alerts').insert({
        patient_id: patientId,
        alert_type: (data.alertType as string) ?? 'clinical_alert',
        severity: normalizeSeverity(data.severity), // CHECK: hijau|kuning|merah
        title: (data.title as string) ?? '',
        description: (data.description as string) ?? '',
        values: Object.keys(valuesPayload).length > 0 ? valuesPayload : null,
        is_read: data.status === 'ACKNOWLEDGED' || data.status === 'RESOLVED' ? true : false,
      });
      if (error) throw new Error(error.message);
    } catch (err) {
      console.error('[SupabaseSync] addClinicalAlert:', err);
      // Alerts are non-critical — don't toast to avoid spamming the user.
    }
  },

  async markAlertRead(patientId: string, alertId: string): Promise<void> {
    try {
      const { error } = await supabase.from('clinical_alerts').update({ is_read: true }).eq('id', alertId);
      if (error) console.error('[SupabaseSync] markAlertRead:', error.message);
    } catch (err) {
      console.error('[SupabaseSync] markAlertRead:', err);
    }
  },

  /** Acknowledge an alert — sets status to ACKNOWLEDGED with who/when.
   *  Pass `existingValues` from the local store to avoid a SELECT round-trip
   *  (which can fail under heavy realtime load). */
  async acknowledgeAlert(alertId: string, acknowledgedBy: string, notes?: string, existingValues?: Record<string, any>): Promise<void> {
    try {
      // Use provided values (from local store) or fall back to a SELECT.
      let baseValues: Record<string, any> = existingValues ?? {};
      if (!existingValues) {
        const { data: current } = await supabase
          .from('clinical_alerts')
          .select('values')
          .eq('id', alertId)
          .single();
        baseValues = (current?.values ?? {}) as Record<string, any>;
      }
      const newValues: Record<string, any> = {
        ...baseValues,
        status: 'ACKNOWLEDGED',
        acknowledgedBy,
        acknowledgedAt: new Date().toISOString(),
      };
      if (notes) {
        const existingNotes = baseValues.notes ? baseValues.notes + '\n---\n' : '';
        newValues.notes = existingNotes + `[${new Date().toISOString()}] ${notes}`;
      }
      const { error } = await supabase
        .from('clinical_alerts')
        .update({ is_read: true, values: newValues })
        .eq('id', alertId);
      if (error) throw new Error(error.message);
    } catch (err) {
      console.error('[SupabaseSync] acknowledgeAlert:', err);
      throw err;
    }
  },

  /** Resolve an alert — sets status to RESOLVED with who/when. */
  async resolveAlert(alertId: string, resolvedBy: string, notes?: string, existingValues?: Record<string, any>): Promise<void> {
    try {
      let baseValues: Record<string, any> = existingValues ?? {};
      if (!existingValues) {
        const { data: current } = await supabase
          .from('clinical_alerts')
          .select('values')
          .eq('id', alertId)
          .single();
        baseValues = (current?.values ?? {}) as Record<string, any>;
      }
      const newValues: Record<string, any> = {
        ...baseValues,
        status: 'RESOLVED',
        resolvedBy,
        resolvedAt: new Date().toISOString(),
      };
      if (notes) {
        const existingNotes = baseValues.notes ? baseValues.notes + '\n---\n' : '';
        newValues.notes = existingNotes + `[${new Date().toISOString()}] ${notes}`;
      }
      const { error } = await supabase
        .from('clinical_alerts')
        .update({ is_read: true, values: newValues })
        .eq('id', alertId);
      if (error) throw new Error(error.message);
    } catch (err) {
      console.error('[SupabaseSync] resolveAlert:', err);
      throw err;
    }
  },

  /** Add a note to an existing alert (merges into values JSONB). */
  async addAlertNote(alertId: string, note: string, existingValues?: Record<string, any>): Promise<void> {
    try {
      let baseValues: Record<string, any> = existingValues ?? {};
      if (!existingValues) {
        const { data: current } = await supabase
          .from('clinical_alerts')
          .select('values')
          .eq('id', alertId)
          .single();
        baseValues = (current?.values ?? {}) as Record<string, any>;
      }
      const existingNotes = baseValues.notes ? baseValues.notes + '\n---\n' : '';
      const newValues = {
        ...baseValues,
        notes: existingNotes + `[${new Date().toISOString()}] ${note}`,
      };
      const { error } = await supabase
        .from('clinical_alerts')
        .update({ values: newValues })
        .eq('id', alertId);
      if (error) throw new Error(error.message);
    } catch (err) {
      console.error('[SupabaseSync] addAlertNote:', err);
    }
  },

  // ── Audit log ──────────────────────────────────────────────────────────
  async addAuditEntry(patientId: string, data: Record<string, unknown>): Promise<void> {
    try {
      // patient_id is a nullable uuid — only forward if it's a real UUID.
      // An empty string ("") would cause "invalid input syntax for type uuid".
      const validPatientId = validUuidOrUndefined(patientId);
      const { error } = await supabase.from('audit_log').insert({
        patient_id: validPatientId ?? null,
        action: (data.action as string) ?? 'clinical_action',
        performed_by: (data.performedBy as string) ?? 'system',
        performed_by_role: (data.performedByRole as string) ?? 'system',
        details: (data.details as any) ?? null,
        ip_address: (data.ipAddress as string) ?? null,
        device: (data.device as string) ?? null,
      });
      if (error) console.error('[SupabaseSync] addAuditEntry:', error.message);
    } catch (err) {
      console.error('[SupabaseSync] addAuditEntry:', err);
    }
  },

  // ── Daily complaints (Keluhan) ──────────────────────────────────────────
  async addKeluhan(patientId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await complaintService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Keluhan Harian', err);
    }
  },

  // ── Resume medis (palliative_resumes table) ────────────────────────────
  /**
   * Insert a resume-medis row into the `palliative_resumes` table via the
   * dedicated `palliativeResumeService`. The service serializes ALL structured
   * fields (dataPasien, ttvSerial, keluhanHarian, skriningPaliatif, esasScores,
   * obat, nutrisi, sosial, acp, aiAnalysis, etc.) into the `full_content`
   * column as a JSON envelope so they survive the round-trip.
   */
  async addResume(patientId: string, data: Record<string, unknown>): Promise<any | null> {
    try {
      return await palliativeResumeService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Resume Medis', err);
      return null;
    }
  },

  async updateResume(patientId: string, resumeId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await palliativeResumeService.update(resumeId, data as any);
    } catch (err) {
      toastSaveError('Update Resume Medis', err);
    }
  },

  // ── Referral letters (referral_letters table) ──────────────────────────
  async addReferralLetter(patientId: string, data: Record<string, unknown>): Promise<any | null> {
    try {
      return await referralLetterService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Surat Rujukan', err);
      return null;
    }
  },

  async updateReferralLetter(patientId: string, letterId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await referralLetterService.update(letterId, data as any);
    } catch (err) {
      toastSaveError('Update Surat Rujukan', err);
    }
  },

  // ── Caregivers (caregivers table) ──────────────────────────────────────
  // NOTE: returns the DB-persisted row (with its real Supabase UUID `id`) so
  // the caller can reconcile the optimistic client-side record. Returning
  // `void` here previously left the store holding a locally-generated id
  // (e.g. "cg-1786...") that never matched the server id, which caused the
  // realtime INSERT handler to treat the row as new and append a duplicate.
  async addCaregiver(patientId: string, data: Record<string, unknown>): Promise<any | null> {
    try {
      return await caregiverService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Caregiver', err);
      return null;
    }
  },

  async updateCaregiver(patientId: string, caregiverId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await caregiverService.update(caregiverId, data as any);
    } catch (err) {
      toastSaveError('Update Caregiver', err);
    }
  },

  async removeCaregiver(patientId: string, caregiverId: string): Promise<void> {
    try {
      await caregiverService.remove(caregiverId);
    } catch (err) {
      console.error('[SupabaseSync] removeCaregiver:', err);
    }
  },

  // ── Family meetings (family_meetings table) ────────────────────────────
  // Returns the DB row so the store can reconcile the temp id → real id
  // (see addCaregiver note above — this is also what fixes the
  // "invalid input syntax for type uuid" error on subsequent updates).
  async addFamilyMeeting(patientId: string, data: Record<string, unknown>): Promise<any | null> {
    try {
      return await familyMeetingService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Pertemuan Keluarga', err);
      return null;
    }
  },

  async updateFamilyMeeting(patientId: string, meetingId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await familyMeetingService.update(meetingId, data as any);
    } catch (err) {
      toastSaveError('Update Pertemuan Keluarga', err);
    }
  },

  // ── Family coordination notes (family_coordination_notes table) ────────
  // Returns the DB row so the store can reconcile the temp id → real id
  // (this is the fix for the "beli obat generik" duplicate-row bug).
  async addFamilyCoordinationNote(patientId: string, data: Record<string, unknown>): Promise<any | null> {
    try {
      return await familyCoordinationNoteService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Catatan Koordinasi', err);
      return null;
    }
  },

  async updateFamilyCoordinationNote(patientId: string, noteId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await familyCoordinationNoteService.update(noteId, data as any);
    } catch (err) {
      toastSaveError('Update Catatan Koordinasi', err);
    }
  },

  // ── Emergency contacts (emergency_contacts table) ──────────────────────
  async addEmergencyContact(patientId: string, data: Record<string, unknown>): Promise<any | null> {
    try {
      return await emergencyContactService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Kontak Darurat', err);
      return null;
    }
  },

  async updateEmergencyContact(patientId: string, contactId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await emergencyContactService.update(contactId, data as any);
    } catch (err) {
      toastSaveError('Update Kontak Darurat', err);
    }
  },

  async removeEmergencyContact(patientId: string, contactId: string): Promise<void> {
    try {
      await emergencyContactService.remove(contactId);
    } catch (err) {
      console.error('[SupabaseSync] removeEmergencyContact:', err);
    }
  },

  // ── Financial support (financial_support table) ────────────────────────
  async addFinancialSupport(patientId: string, data: Record<string, unknown>): Promise<any | null> {
    try {
      return await financialSupportService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Dukungan Finansial', err);
      return null;
    }
  },

  async updateFinancialSupport(patientId: string, recordId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await financialSupportService.update(recordId, data as any);
    } catch (err) {
      toastSaveError('Update Dukungan Finansial', err);
    }
  },

  // ── Transport records (transport_records table) ────────────────────────
  async addTransportRecord(patientId: string, data: Record<string, unknown>): Promise<any | null> {
    try {
      return await transportRecordService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Record Transport', err);
      return null;
    }
  },

  async updateTransportRecord(patientId: string, recordId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await transportRecordService.update(recordId, data as any);
    } catch (err) {
      toastSaveError('Update Record Transport', err);
    }
  },

  // ── Family support materials (family_support_materials table) ─────────
  async addFamilySupportMaterial(patientId: string, data: Record<string, unknown>): Promise<any | null> {
    try {
      return await familySupportMaterialService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Materi Dukungan Keluarga', err);
      return null;
    }
  },

  async updateFamilySupportMaterial(patientId: string, materialId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await familySupportMaterialService.update(materialId, data as any);
    } catch (err) {
      toastSaveError('Update Materi Dukungan Keluarga', err);
    }
  },

  async removeFamilySupportMaterial(patientId: string, materialId: string): Promise<void> {
    try {
      await familySupportMaterialService.remove(materialId);
    } catch (err) {
      console.error('[SupabaseSync] removeFamilySupportMaterial:', err);
    }
  },

  // ── Social assessments (Sosial) ─────────────────────────────────────────
  async addSosial(patientId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await socialService.create({ ...(data as any), palliativePatientId: patientId });
    } catch (err) {
      toastSaveError('Simpan Penilaian Sosial', err);
    }
  },

  async updateSosial(patientId: string, recordId: string, data: Record<string, unknown>): Promise<void> {
    try {
      await socialService.update(recordId, data as any);
    } catch (err) {
      toastSaveError('Update Penilaian Sosial', err);
    }
  },

  // ── AI reports ──────────────────────────────────────────────────────────
  async addAIReport(patientId: string, reportType: string, prompt: string, response: string, metadata?: any): Promise<void> {
    try {
      const { aiService } = await import('@/services/supabase');
      await aiService.save(patientId, reportType, prompt, response, metadata);
    } catch (err) {
      console.error('[SupabaseSync] addAIReport:', err);
      // AI reports are non-critical — don't toast.
    }
  },
};
